channel1:
  dry_point: 27
  enabled: true
  warn_level: 0.2
  wet_point: 3
channel2:
  dry_point: 27
  enabled: true
  warn_level: 0.5
  wet_point: 3
channel3:
  dry_point: 27
  enabled: true
  warn_level: 0.4
  wet_point: 3
general:
  alarm_enable: true
  alarm_interval: 2
mqtt:
  mqtt_host: localhost
  mqtt_port: 1883
  mqtt_username: plantpi
  mqtt_password: pimoroni
  mqtt_debug: false
  mqtt_topic_root: plants/moisture
  interval_s : 30

